import type {
  DegradationPolicy,
  FailoverPlan,
} from "./types.js";

export const samplePolicy: DegradationPolicy = {
  policyVersion: "1.0",
  systemId: "customer-ai",
  maximumFallbackHops: 3,
  minimumProviderDiversity: 3,
  minimumRegionDiversity: 3,
  requireAllScenariosPass: true,
  scenarios: [
    {
      id: "steady-state",
      description: "All inference routes are available.",
      unavailableRouteIds: [],
      unavailableProviders: [],
      unavailableRegions: [],
    },
    {
      id: "primary-model-outage",
      description: "The primary model endpoint is unavailable.",
      unavailableRouteIds: ["atlas-primary"],
      unavailableProviders: [],
      unavailableRegions: [],
    },
    {
      id: "primary-provider-outage",
      description: "The primary cloud provider is unavailable.",
      unavailableRouteIds: [],
      unavailableProviders: ["cloud-a"],
      unavailableRegions: [],
    },
    {
      id: "east-region-outage",
      description: "The primary region is unavailable.",
      unavailableRouteIds: [],
      unavailableProviders: [],
      unavailableRegions: ["us-east"],
    },
    {
      id: "dual-cloud-outage",
      description: "Both external cloud providers are unavailable.",
      unavailableRouteIds: [],
      unavailableProviders: ["cloud-a", "cloud-b"],
      unavailableRegions: [],
    },
  ],
};

const workloads: FailoverPlan["workloads"] = [
  {
    id: "support-assistant",
    primaryRouteId: "atlas-primary",
    dataClass: "confidential",
    requiredCapabilities: ["chat", "json"],
    allowedResidencies: ["US"],
    allowedProviders: ["cloud-a", "cloud-b", "self-hosted"],
    minimumContextWindow: 64_000,
    minimumQualityScore: 80,
    maximumP95LatencyMs: 2_500,
    maximumCostPer1kTokens: 0.04,
    allowInputRetention: false,
    requireConversationState: true,
  },
  {
    id: "automation-agent",
    primaryRouteId: "atlas-primary",
    dataClass: "restricted",
    requiredCapabilities: ["chat", "json", "tools"],
    allowedResidencies: ["US"],
    allowedProviders: ["cloud-a", "cloud-b", "self-hosted"],
    minimumContextWindow: 64_000,
    minimumQualityScore: 82,
    maximumP95LatencyMs: 2_800,
    maximumCostPer1kTokens: 0.05,
    allowInputRetention: false,
    requireConversationState: true,
  },
];

export const resilientPlan: FailoverPlan = {
  planVersion: "1.0",
  systemId: "customer-ai",
  routes: [
    {
      id: "atlas-primary",
      provider: "cloud-a",
      model: "atlas-pro",
      region: "us-east",
      residency: "US",
      capabilities: ["chat", "json", "tools", "vision"],
      acceptedDataClasses: ["public", "internal", "confidential", "restricted"],
      contextWindow: 128_000,
      qualityScore: 96,
      p95LatencyMs: 900,
      costPer1kTokens: 0.03,
      retainsInput: false,
      preservesConversationState: true,
      fallbackIds: ["orbit-secondary", "local-enclave"],
    },
    {
      id: "orbit-secondary",
      provider: "cloud-b",
      model: "orbit-plus",
      region: "us-west",
      residency: "US",
      capabilities: ["chat", "json", "tools"],
      acceptedDataClasses: ["public", "internal", "confidential", "restricted"],
      contextWindow: 96_000,
      qualityScore: 89,
      p95LatencyMs: 1_400,
      costPer1kTokens: 0.035,
      retainsInput: false,
      preservesConversationState: true,
      fallbackIds: ["local-enclave"],
    },
    {
      id: "local-enclave",
      provider: "self-hosted",
      model: "haven-70b",
      region: "us-central",
      residency: "US",
      capabilities: ["chat", "json", "tools"],
      acceptedDataClasses: ["public", "internal", "confidential", "restricted"],
      contextWindow: 64_000,
      qualityScore: 84,
      p95LatencyMs: 2_100,
      costPer1kTokens: 0.018,
      retainsInput: false,
      preservesConversationState: true,
      fallbackIds: [],
    },
  ],
  workloads,
};

export const brittlePlan: FailoverPlan = {
  planVersion: "1.0",
  systemId: "customer-ai",
  routes: [
    {
      ...resilientPlan.routes[0]!,
      fallbackIds: ["external-cheap", "missing-route"],
    },
    {
      id: "external-cheap",
      provider: "cloud-b",
      model: "economy-chat",
      region: "eu-west",
      residency: "EU",
      capabilities: ["chat"],
      acceptedDataClasses: ["public", "internal"],
      contextWindow: 16_000,
      qualityScore: 68,
      p95LatencyMs: 4_500,
      costPer1kTokens: 0.08,
      retainsInput: true,
      preservesConversationState: false,
      fallbackIds: [],
    },
    {
      id: "local-fragile",
      provider: "cloud-a",
      model: "small-local",
      region: "us-east",
      residency: "US",
      capabilities: ["chat"],
      acceptedDataClasses: ["public"],
      contextWindow: 8_000,
      qualityScore: 55,
      p95LatencyMs: 3_500,
      costPer1kTokens: 0.01,
      retainsInput: false,
      preservesConversationState: false,
      fallbackIds: [],
    },
    {
      id: "cycle-a",
      provider: "lab-a",
      model: "cycle-a",
      region: "lab-east",
      residency: "US",
      capabilities: ["chat"],
      acceptedDataClasses: ["public"],
      contextWindow: 8_000,
      qualityScore: 50,
      p95LatencyMs: 5_000,
      costPer1kTokens: 0.01,
      retainsInput: false,
      preservesConversationState: false,
      fallbackIds: ["cycle-b"],
    },
    {
      id: "cycle-b",
      provider: "lab-b",
      model: "cycle-b",
      region: "lab-west",
      residency: "US",
      capabilities: ["chat"],
      acceptedDataClasses: ["public"],
      contextWindow: 8_000,
      qualityScore: 50,
      p95LatencyMs: 5_000,
      costPer1kTokens: 0.01,
      retainsInput: false,
      preservesConversationState: false,
      fallbackIds: ["cycle-a"],
    },
  ],
  workloads,
};
